version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./data/nginx/html:/usr/share/nginx/html
      - ./data/nginx/config:/etc/nginx/conf.d
      - ~/nginx-ssl/certbot/conf:/etc/letsencrypt
      - ~/nginx-ssl/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dito-net

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ~/nginx-ssl/certbot/conf:/etc/letsencrypt
      - ~/nginx-ssl/certbot/www:/var/www/certbot
      - ./data/nginx/html:/usr/share/nginx/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email ditoraharjo@gmail.com --agree-tos --no-eff-email --force-renewal -d ditoraharjo.me

networks:
  dito-net:
    driver: bridge